### ISSUE TITLE
[BUG] NPE with floodgate players

### ISSUE THREAD

**Issue by HaHaWTH** [Niestrat99/AT-Rewritten#109] opened 2023-07-18 14:55 UTC
### Description
When my player joined the server via geyser and floodgate, NullPointException occurred

### Reproducing
Steps to reproduce the behaviour:
1. Join server with geyser and floodgate installed
2. See NPE in console

### Stacktraces
![IMG_2206](https://github.com/Niestrat99/AT-Rewritten/assets/102713261/b25713e4-78fd-4055-b8d3-2f64b112a8dd)
I installed simple stacktrace, if the information isn‘t enough I will add more, feel very sorry about that:(

### Server
Use /version to fill out the following information.
- Purpur 1.20.1-2016

### Plugin Information
Use /version AdvancedTeleport to fill out this information.
- Plugin version: 5.6.12

**Comment by Thatsmusic99** [comment] 2023-07-18 14:58
Duplicate of #58 - if you're on a proxy, make sure you have send-floodgate-data to true and that everything else is set up properly: https://wiki.geysermc.org/geyser/setup/#bungeecordvelocity-setup

If you're unable to do that, then it has been fixed on the [v6 builds](https://github.com/Niestrat99/AT-Rewritten/actions/runs/5567475488)

**Comment by HaHaWTH** [comment] 2023-07-18 15:10
> Duplicate of #58 - if you're on a proxy, make sure you have send-floodgate-data to true and that everything else is set up properly: https://wiki.geysermc.org/geyser/setup/#bungeecordvelocity-setup
> 
> If you're unable to do that, then it has been fixed on the [v6 builds](https://github.com/Niestrat99/AT-Rewritten/actions/runs/5567475488)

I forgot to enable sending floodgate data,  after enable it,  the exception did't appear. But why does AT need to turn it on,  other plugins that hooked floodgate didn't need this to be enabled🧐

**Comment by Thatsmusic99** [comment] 2023-07-18 15:12
It's due to the way it handles player data internally - floodgate kept sending the wrong UUID for the plugin to store internally and fetch players by, had to hook into it manually to fetch the right one, but if send-floodgate-data isn't turned on, it results into that error

v6 approaches it differently and doesn't use the UUID to fetch the player, I may backport this into v5 when I can

**Comment by Jerry080801** [comment] 2023-07-18 15:36
Stop Criticize

**Comment by Thatsmusic99** [comment] 2023-07-18 15:39
> Stop Criticize

I'd consider it a valid question tbh, it's not a standard error found in other plugins

**Comment by Thatsmusic99** [comment] 2023-08-09 17:06
Fix should be in v5.6.13

**Closed by Thatsmusic99** 2023-08-09 17:06 UTC
Labels: duplicate
